"use client";

import { useState } from "react";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Search, Download, ArrowLeft, Loader2, Pill } from "lucide-react"; // Change icon
import { useRecords } from "@/hooks/useRecords";
import { MedicalRecord } from "@/lib/api";
import { cn } from "@/lib/utils";
import Link from "next/link";
import { Skeleton } from "@/components/ui/skeleton";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Badge } from "@/components/ui/badge";

// Configuration - Change these for each page
const CONFIG = {
  category: "Prescription",
  title: "Medication Records",
  icon: Pill,
  emptyMessage: "No medication records found",
};

export default function MedicationPage() {
  const [selectedRecord, setSelectedRecord] = useState<MedicalRecord | null>(null);
  const [searchQuery, setSearchQuery] = useState("");

  const { records, isLoading, loadMore, hasMore } = useRecords({
    category: CONFIG.category,
    autoFetch: true,
  });

  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleDateString('en-US', { 
      day: '2-digit', 
      month: 'short', 
      year: 'numeric' 
    });
  };

  const filteredRecords = records.filter(record =>
    record.patientName?.toLowerCase().includes(searchQuery.toLowerCase()) ||
    record.uploaded_by?.toLowerCase().includes(searchQuery.toLowerCase()) ||
    record.record_data?.toLowerCase().includes(searchQuery.toLowerCase())
  );

  const downloadRecord = (record: MedicalRecord) => {
    const dataStr = JSON.stringify(record, null, 2);
    const dataBlob = new Blob([dataStr], { type: 'application/json' });
    const url = URL.createObjectURL(dataBlob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${CONFIG.category.toLowerCase()}_${record.record_id}.json`;
    link.click();
    URL.revokeObjectURL(url);
  };

  const downloadAllRecords = () => {
    const dataStr = JSON.stringify(filteredRecords, null, 2);
    const dataBlob = new Blob([dataStr], { type: 'application/json' });
    const url = URL.createObjectURL(dataBlob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `all_${CONFIG.category.toLowerCase()}_${new Date().toISOString().split('T')[0]}.json`;
    link.click();
    URL.revokeObjectURL(url);
  };

  // Generate PDF for individual record
  const generatePDF = (record: MedicalRecord) => {
    // Create simple text content for PDF
    const content = `
${CONFIG.title.toUpperCase()}
${'='.repeat(50)}

Record ID: ${record.record_id}
Patient: ${record.patientName || 'N/A'}
Type: ${record.record_type || CONFIG.category}
Date: ${formatDate(record.created_at)}
Facility: ${record.uploaded_by || 'Unknown'}
Status: ${record.verified ? 'Verified' : 'Pending'}

${record.verified ? `
BLOCKCHAIN VERIFICATION
Transaction ID: ${record.blockchainTransactionID}
Hash: ${record.hash_local}
` : ''}

RECORD DETAILS
${'='.repeat(50)}
${record.record_data || 'No additional data'}

${'='.repeat(50)}
Generated on: ${new Date().toLocaleString()}
Generated by: HealthChain Platform
    `.trim();

    // Create blob and download
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${CONFIG.category.toLowerCase()}_${record.record_id}.txt`;
    link.click();
    URL.revokeObjectURL(url);
  };

  if (isLoading && records.length === 0) {
    return <RecordsPageSkeleton />;
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between flex-wrap gap-4">
        <div className="flex items-center gap-4">
          <Link href="/dashboard/resident/records">
            <Button variant="ghost" size="icon">
              <ArrowLeft className="h-5 w-5" />
            </Button>
          </Link>
          <div>
            <h1 className="text-3xl font-bold">{CONFIG.title}</h1>
            <p className="text-muted-foreground">
              {filteredRecords.length} record{filteredRecords.length !== 1 ? 's' : ''} found
            </p>
          </div>
        </div>
        <Button onClick={downloadAllRecords} disabled={filteredRecords.length === 0}>
          <Download className="mr-2 h-4 w-4" />
          Download All
        </Button>
      </div>

      <div className="relative max-w-md">
        <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-muted-foreground" />
        <Input
          type="search"
          placeholder={`Search ${CONFIG.title.toLowerCase()}...`}
          value={searchQuery}
          onChange={(e) => setSearchQuery(e.target.value)}
          className="pl-10"
        />
      </div>

      <Card className="shadow-lg border-none">
        <CardContent className="p-6">
          {filteredRecords.length === 0 ? (
            <div className="text-center py-12">
              <CONFIG.icon className="h-12 w-12 text-muted-foreground mx-auto mb-4" />
              <p className="text-muted-foreground">
                {searchQuery ? `No records found matching your search` : CONFIG.emptyMessage}
              </p>
            </div>
          ) : (
            <>
              <div className="overflow-x-auto">
                <Table>
                  <TableHeader>
                    <TableRow className="bg-muted/50">
                      <TableHead>DATE</TableHead>
                      <TableHead>TYPE</TableHead>
                      <TableHead>FACILITY</TableHead>
                      <TableHead>PATIENT</TableHead>
                      <TableHead>STATUS</TableHead>
                      <TableHead className="text-right">ACTIONS</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {filteredRecords.map((record) => (
                      <TableRow
                        key={record.record_id}
                        className="cursor-pointer hover:bg-muted/50"
                        onClick={() => setSelectedRecord(record)}
                      >
                        <TableCell className="font-medium">
                          {formatDate(record.created_at)}
                        </TableCell>
                        <TableCell>{record.record_type || CONFIG.category}</TableCell>
                        <TableCell>{record.uploaded_by || "Unknown"}</TableCell>
                        <TableCell>{record.patientName || "N/A"}</TableCell>
                        <TableCell>
                          <Badge variant={record.verified ? "default" : "secondary"}>
                            {record.verified ? "Verified" : "Pending"}
                          </Badge>
                        </TableCell>
                        <TableCell className="text-right">
                          <Button
                            variant="ghost"
                            size="sm"
                            onClick={(e) => {
                              e.stopPropagation();
                              downloadRecord(record);
                            }}
                          >
                            <Download className="h-4 w-4" />
                          </Button>
                        </TableCell>
                      </TableRow>
                    ))}
                  </TableBody>
                </Table>
              </div>

              {hasMore && (
                <div className="flex justify-center mt-6">
                  <Button 
                    variant="outline" 
                    onClick={loadMore}
                    disabled={isLoading}
                  >
                    {isLoading ? (
                      <>
                        <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                        Loading...
                      </>
                    ) : (
                      "Load More"
                    )}
                  </Button>
                </div>
              )}
            </>
          )}
        </CardContent>
      </Card>

      <RecordModal
        record={selectedRecord}
        open={!!selectedRecord}
        onClose={() => setSelectedRecord(null)}
        onDownload={downloadRecord}
        onDownloadPDF={generatePDF}
        config={CONFIG}
      />
    </div>
  );
}

function RecordModal({ 
  record, 
  open, 
  onClose,
  onDownload,
  onDownloadPDF,
  config
}: { 
  record: MedicalRecord | null; 
  open: boolean; 
  onClose: () => void;
  onDownload: (record: MedicalRecord) => void;
  onDownloadPDF: (record: MedicalRecord) => void;
  config: typeof CONFIG;
}) {
  if (!record) return null;

  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleDateString('en-US', { 
      day: '2-digit',
      month: 'short', 
      year: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    });
  };

  const parseRecordData = (recordData: string) => {
    try {
      return JSON.parse(recordData);
    } catch {
      return null;
    }
  };

  const parsedData = parseRecordData(record.record_data);

  return (
    <Dialog open={open} onOpenChange={onClose}>
      <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="text-2xl flex items-center gap-2">
            <config.icon className="h-6 w-6" />
            {record.record_type || config.category}
          </DialogTitle>
          <DialogDescription>
            {formatDate(record.created_at)}
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-6 mt-4">
          <div className={cn(
            "flex items-center gap-2 p-3 rounded-lg",
            record.verified 
              ? "bg-green-50 border border-green-200" 
              : "bg-yellow-50 border border-yellow-200"
          )}>
            <span className={cn(
              "h-2 w-2 rounded-full",
              record.verified ? "bg-green-500" : "bg-yellow-500"
            )}></span>
            <span className={cn(
              "text-sm font-medium",
              record.verified ? "text-green-900" : "text-yellow-900"
            )}>
              {record.verified ? "Verified on Blockchain" : "Pending Verification"}
            </span>
          </div>

          <div className="grid grid-cols-2 gap-4">
            <InfoItem label="Patient Name" value={record.patientName} />
            <InfoItem label="Type" value={record.record_type} />
            <InfoItem label="Facility" value={record.uploaded_by} />
            <InfoItem label="Date" value={formatDate(record.created_at)} />
          </div>

          {parsedData && (
            <div className="space-y-2">
              <h3 className="font-semibold text-lg">Details</h3>
              <div className="bg-muted/50 p-4 rounded-lg space-y-2">
                {Object.entries(parsedData).map(([key, value]) => (
                  <div key={key} className="flex justify-between text-sm">
                    <span className="text-muted-foreground capitalize">
                      {key.replace(/_/g, ' ')}:
                    </span>
                    <span className="font-medium">{String(value)}</span>
                  </div>
                ))}
              </div>
            </div>
          )}

          {!parsedData && record.record_data && (
            <div className="space-y-2">
              <h3 className="font-semibold text-lg">Record Details</h3>
              <p className="text-sm text-muted-foreground leading-relaxed">
                {record.record_data}
              </p>
            </div>
          )}

          {record.verified && (
            <div className="space-y-2">
              <h3 className="font-semibold text-lg">Blockchain Verification</h3>
              <div className="space-y-2">
                <div className="bg-muted/50 p-3 rounded-lg">
                  <p className="text-xs text-muted-foreground mb-1">Transaction ID</p>
                  <p className="text-xs font-mono break-all">{record.blockchainTransactionID}</p>
                </div>
                <div className="bg-muted/50 p-3 rounded-lg">
                  <p className="text-xs text-muted-foreground mb-1">Hash</p>
                  <p className="text-xs font-mono break-all">{record.hash_local}</p>
                </div>
              </div>
            </div>
          )}

          <div className="grid grid-cols-3 gap-2 pt-4 border-t">
            <Button 
              variant="outline"
              onClick={() => onDownload(record)}
            >
              <Download className="mr-2 h-4 w-4" />
              JSON
            </Button>
            <Button 
              variant="outline"
              onClick={() => onDownloadPDF(record)}
            >
              <Download className="mr-2 h-4 w-4" />
              PDF
            </Button>
            <Button 
              variant="outline"
              onClick={onClose}
            >
              Close
            </Button>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}

function InfoItem({ label, value }: { label: string; value: string }) {
  return (
    <div>
      <p className="text-xs text-muted-foreground">{label}</p>
      <p className="text-sm font-medium">{value || "N/A"}</p>
    </div>
  );
}

function RecordsPageSkeleton() {
  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-4">
          <Skeleton className="h-10 w-10" />
          <div>
            <Skeleton className="h-8 w-[200px] mb-2" />
            <Skeleton className="h-4 w-[150px]" />
          </div>
        </div>
        <Skeleton className="h-10 w-[150px]" />
      </div>
      <Skeleton className="h-10 w-[300px]" />
      <Card className="p-6">
        <div className="space-y-3">
          {[...Array(5)].map((_, i) => (
            <Skeleton key={i} className="h-12 w-full" />
          ))}
        </div>
      </Card>
    </div>
  );
}