import { renderDetailPanel } from '../_details/DetailRenderMapper';

interface AlertsDetailWrapperProps {
    alert: any;
    onClose: () => void;
}

export const AlertsDetailWrapper: React.FC<AlertsDetailWrapperProps> = ({ alert, onClose }) => {
    return (
        <div className="fixed inset-y-0 right-0 z-20 w-full lg:relative lg:w-[450px]">
            <div className="w-full h-full bg-white border-none shadow-xl p-6 overflow-y-auto">
                {renderDetailPanel(alert, onClose)}
                
                {/* Audit Log (Consistent across all details) */}
                <div className="mt-6 space-y-3">
                    <h4 className="text-md font-semibold border-b border-gray-200 pb-1">Audit Log</h4>
                    <p className="text-xs text-muted-foreground">Alert generated by automated risk engine on 08:22 AM</p>
                </div>
            </div>
        </div>
    );
};